export const TRANSACTION_INIT_START = 'TRANSACTION_INIT_START';
export const TRANSACTION_INIT_SUCCESS = 'TRANSACTION_INIT_SUCCESS';
export const TRANSACTION_INIT_FAILURE = 'TRANSACTION_INIT_FAILURE';
export const TRANSACTION_INIT_REFRESH = 'TRANSACTION_INIT_REFRESH';
export const LOG_OUT = 'LOG-OUT';
