export const GET_CARDS_DATA_START = 'GET_CARDS_DATA_START';
export const GET_CARDS_DATA_SUCCESS = 'GET_CARDS_DATA_SUCCESS';
export const GET_CARDS_DATA_FAILURE = 'GET_CARDS_DATA_SUCCESS';
export const LOG_OUT = 'LOG-OUT';
