export const DELETE_CARD_START = 'DELETE_CARD_START';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';
export const CLEAR_DELETE_CARD_DATA = 'CLEAR_DELETE_CARD_DATA';
export const LOG_OUT = 'LOG-OUT';
