export const SET_REGISTRATION_PASSWORDS_START =
  'SET_REGISTRATION_PASSWORDS_START';
export const SET_REGISTRATION_PASSWORDS_SUCCESS =
  'SET_REGISTRATION_PASSWORDS_SUCCESS';
export const SET_REGISTRATION_PASSWORDS_FAILURE =
  'SET_REGISTRATION_PASSWORDS_FAILURE';

export const SET_ANONYMOUS_TYPE_START = 'SET_ANONYMOUS_TYPE_START';
export const SET_ANONYMOUS_TYPE_SUCCESS = 'SET_ANONYMOUS_TYPE_SUCCESS';
export const SET_ANONYMOUS_TYPE_FAILURE = 'SET_ANONYMOUS_TYPE_FAILURE';
export const LOG_OUT = 'LOG-OUT';
