export const RESENT_PHONE_NUMBER_START = 'RESENT_PHONE_NUMBER_START';
export const RESENT_PHONE_NUMBER_SUCCESS = 'RESENT_PHONE_NUMBER_SUCCESS';
export const RESENT_PHONE_NUMBER_FAILURE = 'RESENT_PHONE_NUMBER_FAILURE';
export const REFRESH_RESENT_PHONE_NUMBER_DATA = 'REFRESH_CONFIRM_PHONE_DATA';
export const LOG_OUT = 'LOG-OUT';
