export const GET_CARD_INFO_DATA_FAILURE = 'GET_CARD_INFO_DATA_FAILURE';
export const GET_CARD_INFO_DATA_START = 'GET_CARD_INFO_DATA_START';
export const GET_CARD_INFO_DATA_SUCCESS = 'GET_CARD_INFO_DATA_SUCCESS';
export const LOG_OUT = 'LOG-OUT';
