export const SET_RESTORE_PASSWORD_START = 'SET_RESTORE_PASSWORD_START';
export const SET_RESTORE_PASSWORD_SUCCESS = 'SET_RESTORE_PASSWORD_SUCCESS';
export const SET_RESTORE_PASSWORD_FAILURE = 'SET_RESTORE_PASSWORD_FAILURE';
export const SET_RESTORE_DATA_START = 'SET_RESTORE_DATA_START';
export const SET_RESTORE_DATA_SUCCESS = 'SET_RESTORE_DATA_SUCCESS';
export const SET_RESTORE_DATA_FAILURE = 'SET_RESTORE_DATA_FAILURE';
export const SET_RESTORE_PASSWORD_CREATE_START =
  'SET_RESTORE_PASSWORD_CREATE_START ';
export const SET_RESTORE_PASSWORD_CREATE_SUCCESS =
  'SET_RESTORE_PASSWORD_CREATE_SUCCESS';
export const SET_RESTORE_PASSWORD_CREATE_FAILURE =
  'SET_RESTORE_PASSWORD_CREATE_FAILURE';
export const RESET_RESTORE_PASSWORD = 'RESET_RESTORE_PASSWORD';
export const LOG_OUT = 'LOG-OUT';
