export const TRANSACTION_DELAY_START = 'TRANSACTION_DELAY_START';
export const TRANSACTION_DELAY_SUCCESS = 'TRANSACTION_DELAY_SUCCESS';
export const TRANSACTION_DELAY_FAILURE = 'TRANSACTION_DELAY_FAILURE';
export const TRANSACTION_DELAY_CLEAR = 'TRANSACTION_DELAY_CLEAR';
export const LOG_OUT = 'LOG-OUT';
