export const SEND_CARD_DATA_START = 'SEND_CARD_DATA_START';
export const SEND_CARD_DATA_SUCCESS = 'SEND_CARD_DATA_SUCCESS';
export const SEND_CARD_DATA_FAILURE = 'SEND_CARD_DATA_FAILURE';
export const REFRESH_CARD_DATA = 'REFRESH_CARD_DATA';
export const LOG_OUT = 'LOG-OUT';
