export const SET_REGISTRATION_EMAIL_START = 'SET_REGISTRATION_EMAIL_START';
export const SET_REGISTRATION_EMAIL_SUCCESS = 'SET_REGISTRATION_EMAIL_SUCCESS';
export const SET_REGISTRATION_EMAIL_FAILURE = 'SET_REGISTRATION_EMAIL_FAILURE';
export const REFRESH_REGISTRATION_EMAIL = 'REFRESH_REGISTRATION_EMAIL';

export const SET_REGISTRATION_CONFIRM_EMAIL_START =
  'SET_REGISTRATION_CONFIRM_EMAIL_START';
export const SET_REGISTRATION_CONFIRM_EMAIL_SUCCESS =
  'SET_REGISTRATION_CONFIRM_EMAIL_SUCCESS';
export const SET_REGISTRATION_CONFIRM_EMAIL_FAILURE =
  'SET_REGISTRATION_CONFIRM_EMAIL_FAILURE';
export const LOG_OUT = 'LOG-OUT';
