export const RESENT_EMAIL_CODE_FAILURE = 'RESENT_EMAIL_CODE_FAILURE';
export const RESENT_EMAIL_CODE_SUCCESS = 'RESENT_EMAIL_CODE_SUCCESS';
export const RESENT_EMAIL_CODE_START = 'RESENT_EMAIL_CODE_START';
export const REFRESH_RESENT_EMAIL_CODE_DATA = 'REFRESH_RESENT_EMAIL_CODE_DATA';
export const LOG_OUT = 'LOG-OUT';
