export const LOGIN_USER_DATA_START = 'LOGIN_USER_DATA_START ';
export const LOGIN_USER_DATA_SUCCESS = 'LOGIN_USER_DATA_SUCCESS ';
export const LOGIN_USER_DATA_FAILURE = 'LOGIN_USER_DATA_FAILURE';
export const REFRESH_USER_DATA = 'REFRESH_USER_DATA ';
export const LOG_OUT = 'LOG-OUT';
