export const GET_FULL_NAME = 'GET_FULL_NAME';
export const CREATE_PERSONAL_INFO = 'CREATE_PERSONAL_INFO';
export const GET_PHONE_NUMBER = 'GET_PHONE_NUMBER';
export const SET_REGISTRATION_DATA_START = 'SET_REGISTRATION_DATA_START';
export const SET_REGISTRATION_DATA_SUCCESS = 'SET_REGISTRATION_DATA_SUCCESS';
export const SET_REGISTRATION_DATA_FAILURE = 'SET_REGISTRATION_DATA_FAILURE';
export const REFRESH_REGISTRATION_DATA = 'REFRESH_REGISTRATION_DATA';
export const SET_REGISTRATION_CONFIRM_PHONE_CODE_START =
  'SET_REGISTRATION_CONFIRM_PHONE_CODE_START';
export const SET_REGISTRATION_CONFIRM_PHONE_CODE_SUCCESS =
  'SET_REGISTRATION_CONFIRM_PHONE_CODE_SUCCESS';
export const SET_REGISTRATION_CONFIRM_PHONE_CODE_FAILURE =
  'SET_REGISTRATION_CONFIRM_PHONE_CODE_FAILURE';
export const REFRESH_CONFIRM_PHONE_DATA = 'REFRESH_CONFIRM_PHONE_DATA';
export const REFRESH_REGISTRATION_PHONE_NUMBER_DATA =
  'REFRESH_REGISTRATION_PHONE_NUMBER_DATA';
export const LOG_OUT = 'LOG-OUT';
